[package]
name = "faucet-server"
version = "0.4.1"
edition = "2021"
authors = ["Andrés F. Quintero <afquinteromoreano@gmail.com>"]
description = "Welcome to Faucet, your go-to solution for deploying Plumber APIs and Shiny Applications with blazing speed and efficiency. Faucet is a high-performance server built with Rust, offering Round Robin and Round Robin + IP Hash load balancing for seamless scaling and distribution of your R applications. Whether you're a data scientist, developer, or DevOps enthusiast, Faucet streamlines the deployment process, making it easier than ever to manage replicas and balance loads effectively."
license = "MIT"
default-run = "faucet"
readme = "README.md"
homepage = "https://github.com/andyquinterom/Faucet"
repository = "https://github.com/andyquinterom/Faucet"
keywords = ["R", "loadbalancer", "server", "plumber", "shiny"]

[[bin]]
name = "faucet"
path = "src/main.rs"

[dependencies]
async-trait = "0.1.74"
clap = { version = "4.4.10", features = ["derive", "env"] }
deadpool = { version = "0.10.0", features = ["rt_tokio_1"] }
env_logger = "0.10.1"
http-body-util = "0.1.0"
hyper = { version = "1.0.1", features = ["full"] }
hyper-util = { version = "0.1.1", features = ["full"] }
log = "0.4.20"
num_cpus = "1.16.0"
tokio = { version = "1.34.0", features = ["full"] }
tokio-stream = "0.1.14"
tokio-util = { version = "^0.7", features = ["codec"] }
tokio-tungstenite = "^0.21"
base64 = "0.21.5"
sha1 = "0.10.6"
